name: Build (Fabric 1.21.x)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # Inject Fabric Maven into pluginManagement at build time (no repo changes needed)
      - name: Inject Fabric Maven for plugin resolution
        run: |
          mkdir -p ~/.gradle/init.d
          cat > ~/.gradle/init.d/loom-plugin-repos.gradle << 'EOF'
          // Ensures the Loom plugin can be resolved on CI even if settings.gradle
          // doesn't declare pluginManagement repositories.
          settingsEvaluated { settings ->
              settings.pluginManagement.repositories {
                  maven { url = uri("https://maven.fabricmc.net/") }
                  gradlePluginPortal()
                  mavenCentral()
              }
          }
          EOF

      # Uses Gradle without needing a wrapper in-repo
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.8
          arguments: build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: seed-sync-jar
          path: build/libs/*.jar
