# .github/workflows/build.yml
name: Build (Seed Sync Fabric)

on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      # Optional sanity check (nice to have)
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      # Enable Gradle build cache & dependency caching (uses your wrapper)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build (no-daemon)
        run: ./gradlew --no-daemon clean build

      - name: Upload JARs
        uses: actions/upload-artifact@v4
        with:
          name: seed-sync-build
          path: build/libs/*.jar
          if-no-files-found: error

  # Optional: publish a release when you push a tag like v0.1.0
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: seed-sync-build
          path: artifacts
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
