name: Build (Fabric 1.21.x)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # 🔧 Inject Fabric Maven for plugin resolution (no repo changes needed)
      - name: Inject Loom plugin repositories
        run: |
          mkdir -p ~/.gradle/init.d
          cat > ~/.gradle/init.d/loom-plugin-repos.gradle << 'EOF'
          // Ensure fabric-loom can be resolved during pluginManagement on CI
          settingsEvaluated { settings ->
              settings.pluginManagement.repositories {
                  maven { url = uri("https://maven.fabricmc.net/") }
                  gradlePluginPortal()
                  mavenCentral()
              }
              // Be explicit about how to resolve the Loom plugin module
              settings.pluginManagement.resolutionStrategy.eachPlugin { req ->
                  if (req.requested.id.id == "fabric-loom" && req.requested.version != null) {
                      useModule("fabric-loom:fabric-loom.gradle.plugin:${req.requested.version}")
                  }
              }
          }
          EOF

      # Optional: see Gradle + JDK versions in logs
      - name: Gradle version
        run: echo "Gradle will be installed by the action below (8.8)" && java -version

      # ✅ Build with a managed Gradle (no wrapper needed)
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.8
          # Pass the init script explicitly (init.d also auto-loads; this makes it bulletproof)
          arguments: --init-script ~/.gradle/init.d/loom-plugin-repos.gradle build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: seed-sync-jar
          path: build/libs/*.jar
