name: Build (Fabric 1.21.x)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # Ensure Loom can be found + map 1.11 -> 1.11.7 if requested
      - name: Inject Loom plugin repositories
        run: |
          mkdir -p "$HOME/.gradle/init.d"
          cat > "$HOME/.gradle/init.d/loom-plugin-repos.gradle" << 'EOF'
          // Make Loom resolvable on CI even if settings.gradle lacks pluginManagement
          settingsEvaluated { settings ->
              settings.pluginManagement.repositories {
                  maven { url = uri("https://maven.fabricmc.net/") }
                  gradlePluginPortal()
                  mavenCentral()
              }
              // If the build asks for "fabric-loom:1.11", redirect to a real published version.
              settings.pluginManagement.resolutionStrategy.eachPlugin { req ->
                  if (req.requested.id.id == "fabric-loom") {
                      if (req.requested.version == "1.11") {
                          useModule("fabric-loom:fabric-loom.gradle.plugin:1.11.7")
                      } else if (req.requested.version != null) {
                          // Ensure we resolve the marker from Fabric's Maven for any other version.
                          useModule("fabric-loom:fabric-loom.gradle.plugin:${req.requested.version}")
                      }
                  }
              }
          }
          EOF
          echo "Created init script at $HOME/.gradle/init.d/loom-plugin-repos.gradle"
          ls -al "$HOME/.gradle/init.d"

      # Build with a managed Gradle (no wrapper needed)
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.12
          arguments: clean build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: seed-sync-jar
          path: build/libs/*.jar
